config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :articles do
    resources :comments
  end
  resources :pdfs
  resources :fillablepdfs
  resources :dashboards
  root 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                      length: { minimum: 5 }
    has_one_attached :avatar
  end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show, :edit]
    
    def index
    @articles = Article.all
    respond_to do |format|
      format.html
        format.pdf do 
          pdf = ArticlePdf.new(@articles)
          send_data pdf.render, 
            filename: 'articles.pdf', 
            type: 'application/pdf', 
            dispostion: 'inline'
        end
      end
    end
    
    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def edit
      @article = Article.find(params[:id])
    end

    def create
      @article = Article.new(article_params)
 
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end

    def update
      @article = Article.find(params[:id])
      
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
    
      redirect_to articles_path
    end
   
    private
    def article_params
      params.require(:article).permit(:title, :text, :avatar)
    end
  end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    <p>
    <% if @article.avatar.attached? %>
      <%= image_tag @article.avatar, style: "width:100px; display:block;" %>
    <% end %>
      <%= form.label :avatar %><br>
      <%= form.file_field :avatar %>
    </p>
    
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

  

app/views/articles/_modal.html.erb
<p><button data-micromodal-trigger="modal-1">Click here to open the modal!</button></p>
<div class="modal micromodal-slide" id="modal-1" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
      <header class="modal__header">
        <h2 class="modal__title" id="modal-1-title">
          Micromodal
        </h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
      </header>
      <main class="modal__content" id="modal-1-content">
        <p>
        Try hitting the <code>tab</code> key and notice how the focus stays within the modal itself. Also, <code>esc</code> to close modal.
        </p>
      </main>
      <footer class="modal__footer">
        <button class="modal__btn modal__btn-primary">Continue</button>
        <button class="modal__btn" data-micromodal-close aria-label="Close this dialog window">Close</button>
      </footer>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div style="background-color:rgb(239, 200, 247); padding:5px;">
  <h1>Listing Articles</h1>
</div>
<div style="background-color:rgb(173, 220, 237); padding:5px;">
  <%= link_to 'New article', new_article_path %> <br>
  <%= link_to "PDF File", articles_path(format: 'pdf')%>
</div>
<div style="background-color:rgb(195, 247, 205); padding:5px;">
  <%= link_to 'Upload PDF', pdfs_path %>
</div>
<div style="background-color:rgb(247, 245, 181); padding:5px;">
  <%= link_to 'Upload fillable PDF', fillablepdfs_path %>
</div>
<div style="background-color:rgb(255, 202, 124); padding:5px;">
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>
<% if @article.avatar.attached? %>
    <%= image_tag @article.avatar, style: "width:100px; display:block;" %>
<% else %>
    <p>no image</p>
<% end %>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>