config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :articles do
    resources :comments
  end
  resources :pdfs
  resources :fillablepdfs
  resources :dashboards
  root 'welcome#index'
end

app/models/pdf.rb
class Pdf < ApplicationRecord
    has_one_attached :pdf_file
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
    def index
        @pdf = Pdf.new
    end

    def show
        @pdf = Pdf.find(params[:id])
        @pdf_length = 0

        def save_png_images(to_image_temp_path, index, page)
          image_file = "#{to_image_temp_path}/#{index+1}.png"
          MiniMagick::Tool::Convert.new do |convert|
            convert << page.path
            convert.resize("600X600")
            convert << image_file
          end
        end

        image = MiniMagick::Image.open @pdf.pdf_file
        image.pages.each_with_index do |page, index|
          save_png_images("app/assets/images", index, page)
          @pdf_length += 1
        end
    end

    def create
      @pdf = Pdf.new(pdf_params)

      if @pdf.save
        redirect_to @pdf
      else
        render 'new'
      end
    end

    private
    def pdf_params
      params.require(:pdf).permit(:name, :pdf_file)
    end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/pdfs/index.html.erb
<div style="background-color:rgb(195, 247, 205); padding:5px;">
    <%= form_with model: @pdf, local:true do |form| %>
        <p>
        <%= form.label :name %><br>
        <%= form.text_area :name %>
        </p>
        <p>
        <%= form.label :pdf_file %><br>
        <%= form.file_field :pdf_file %>
        </p>
        <p>
        <%= form.submit "Attach PDF"%>
        </p>
    <% end %>
</div>

app/views/pdfs/show.html.erb
<div style="background-color:rgb(195, 247, 205); padding:5px;">
    <% if @pdf.pdf_file.attached? %>
        <h1><%= @pdf.name %> was successfully attached</h1>
        <% for i in 1..@pdf_length%>
            <%= image_tag ("/assets/#{i}.png")%>
        <% end %>
    <% else %>
        <h1>Error: Something went wrong</h1>
    <% end %>
</p>
<%= link_to 'Back', articles_path %>
</div>